const types = Object.freeze({
    SET_TASKS: 'SET_TASKS',
    DELETE_ONE_TASK: 'DELETE_ONE_TASK',
    SET_DELETE_TASK_ID: 'SET_DELETE_TASK_ID',
    SET_OR_REMOVE_LOADING: 'SET_OR_REMOVE_LOADING',
    TOGLE_ADD_TASK_MODAL: 'TOGLE_ADD_TASK_MODAL',
    ADD_TASK: 'ADD_TASK',
    TOGGLE_CONFIRM_MODAL: 'TOGGLE_CONFIRM_MODAL',
    TOGGLE_CHECK_TASK: 'TOGGLE_CHECK_TASK',
    DELETE_CHECKED_TASK: 'DELETE_CHECKED_TASK',
    TOGGLE_EDITE_MODAL: 'TOGGLE_EDITE_MODAL',
    SET_SINGLE_TASKS: 'SET_SINGLE_TASKS',
    SET_IS_OPEN_CONFIRM: 'SET_IS_OPEN_CONFIRM',
    SET_EDITE_TASK: 'SET_EDITE_TASK',
    EDIT_TASK: 'EDIT_TASK',
    CHECKED_ALL_TAKS: 'CHECKED_ALL_TAKS',
    RESET_DATA: 'RESET_DATA',
    SET_SINGLE_TASK: 'SET_SINGLE_TASK',
    TOGGLE_SINGLE_TASK_EDIT_MODAL: 'TOGGLE_SINGLE_TASK_EDIT_MODAL',
    RESET_SINGLE_TASK_STATE: 'RESET_SINGLE_TASK_STATE',
});

export default types;
